# Generated by Django 3.2.12 on 2023-06-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeastarieti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_sms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
