# Generated by Django 4.2.2 on 2023-06-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeastarieti', '0002_user_current_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
