# Generated by Django 4.2.2 on 2023-06-12 15:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yeastarieti', '0003_user_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9, message='El número de teléfono debe tener 9 dígitos.'), django.core.validators.MaxLengthValidator(9, message='El número de teléfono debe tener 9 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9, message='El número de teléfono debe tener 9 dígitos.'), django.core.validators.MaxLengthValidator(9, message='El número de teléfono debe tener 9 dígitos.')]),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=20)),
                ('num_contact', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9, message='El número de teléfono debe tener 9 dígitos.'), django.core.validators.MaxLengthValidator(9, message='El número de teléfono debe tener 9 dígitos.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
